### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by concon121** [concon121/atom-commit-templates#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-commit-templates](https://github.com/concon121/atom-commit-templates) package 0.1.2

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at InputDialog.callback (/packages/atom-commit-templates/lib/index.js:35:27)
    at InputDialog.confirm (/packages/atom-commit-templates/node_modules/@aki77/atom-input-dialog/src/input-dialog.js:48:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
 13x -5:06.0 blur (input.hidden-input)
     -5:02.8.0 platformio-ide-terminal:toggle (textarea.)
  7x -5:02.3.0 blur (textarea.)
     -3:26 atom-commit-templates:Set Commit Template (input.hidden-input)
  7x -3:26 blur (input.hidden-input)
     -2:05.3.0 atom-commit-templates:Set Commit Template (input.hidden-input)
  7x -2:05.3.0 blur (input.hidden-input)
     -1:14.6.0 atom-commit-templates:Set Commit Template (input.hidden-input)
  6x -1:14.6.0 blur (input.hidden-input)
     -0:45.3.0 atom-commit-templates:Set Commit Template (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:45.3.0 blur (atom-text-editor.editor.mini)
     -0:21.9.0 core:backspace (input.hidden-input)
     -0:20.2.0 core:confirm (input.hidden-input)
  4x -0:16.9.0 blur (input.hidden-input)
     -0:14.2.0 core:copy (span.syntax--text.syntax--plain.syntax--null-grammar)
  9x -0:13.8.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-cform-yaml 0.5.1-0 
atom-clock 0.1.15 
atom-commit-templates 0.1.2 
atom-python-test 0.7.0 
autocomplete-js-import 1.4.0 
autocomplete-json 5.5.0 
autocomplete-python 1.10.3 
autocomplete-xml 0.9.4 
busy-signal 1.4.3 
codesidestory-atom 0.2.1 
ex-mode 0.18.0 
file-icons 2.1.12 
file-types 0.5.5 
gherkin-autocomplete 2.0.0 
git-control 0.9.0 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
json-path-finder 0.1.9 
language-gherkin 1.0.4 
language-yaml-cloudformation 0.3.1 
line-count 0.5.0 
linter 2.2.0 
linter-erb 1.1.0 
linter-eslint 8.3.2 
linter-javac 1.9.4 
linter-js-cloudformation-yaml 2.2.1 
linter-js-standard 4.0.2 
linter-js-yaml 1.2.8 
linter-jshint 3.1.6 
linter-json-lint 0.1.2 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-pylint 2.1.0 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
python-indent 1.1.0 
python-iresolve 0.0.3 
python-isort 0.0.7 
python-snippets 1.9.0 
script 3.16.0 
sort-lines 0.15.0 
split-diff 1.5.1 
sync-settings 0.8.3 
tabs-to-spaces 1.0.3 
tool-bar 1.1.0 
tool-bar-atom 1.7.0 
trailing-spaces 0.4.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
tree-view-search-bar 0.1.8 
vim-mode-plus 1.8.0 
wordcount 2.10.4 
xml-tools 0.2.1 
```

**Comment by concon121** [comment]
Will be resolved in the next release version 0.1.3
